### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by demesameneshoa** [Luffytaro22/Leaderboard#4]
### Highlights 🟢 
-  Your code is clean and readable
-  You have added all the required functionalities
-  Great UI 
### Recommendations ♻️ 
- Try to add a scroll on the score list to improve users experience when there is multiple scored
-  It would be better if you could remove the class as it has provided very small purpose in your code
-  The submit button is not expected to refresh your scores list, which will make the refresh button redundant

**Comment by Luffytaro22** [comment]
Thanks, @demesameneshoa and @Kidd254 for your nice feedback! 😎
